name: kami
description: Team Raiju's bot controller app
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  flutter_reactive_ble: ^5.2.0
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_launcher_icons:
  android: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 30
  adaptive_icon_background: "#330b56"
  adaptive_icon_foreground: "assets/img/icon_fg.png"
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
